MySQL:  #Here you can edit your MySQL database configuration
  enable: true   #You must first set to true to activate the MySQL service
  User: user
  Password: password
  Database: minecraft
  Host: localhost
  Port: "3306"